import jsPDF from "jspdf";

export function generateChecklistPDF(selectedLicenses, licenseDocuments) {
  const doc = new jsPDF();
  
  // Set document properties
  doc.setProperties({
    title: "PRONTO360 License Document Checklist",
    subject: "Required Documents for Medical Licenses",
    author: "PRONTO360 Compliance Assistant",
    keywords: "medical, license, documents, checklist"
  });

  let yPosition = 20;
  const pageWidth = doc.internal.pageSize.width;
  const margin = 20;

  // Add title
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("PRONTO360 License Document Checklist", margin, yPosition);
  yPosition += 15;

  // Add subtitle
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("Generated by PRONTO360 Compliance Assistant", margin, yPosition);
  yPosition += 5;
  
  const date = new Date().toLocaleDateString();
  doc.text(`Generated on: ${date}`, margin, yPosition);
  yPosition += 20;

  // Add content for each license
  selectedLicenses.forEach((license, index) => {
    // Check if we need a new page
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }

    // License header
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(37, 99, 235); // Blue color
    doc.text(`${index + 1}. ${license.name}`, margin, yPosition);
    yPosition += 8;

    // License description
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(0, 0, 0); // Black color
    const description = license.description || "No description available";
    const splitDescription = doc.splitTextToSize(description, pageWidth - 2 * margin);
    doc.text(splitDescription, margin, yPosition);
    yPosition += splitDescription.length * 5 + 5;

    // Documents section
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Required Documents:", margin, yPosition);
    yPosition += 8;

    // Get documents for this license
    const docData = licenseDocuments[license.id];
    if (docData && docData.documents) {
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      
      docData.documents.forEach((item, itemIndex) => {
        // Check if we need a new page
        if (yPosition > 270) {
          doc.addPage();
          yPosition = 20;
        }

        // Document item
        doc.text(`${itemIndex + 1}. ${item.name}`, margin + 5, yPosition);
        yPosition += 6;
        
        // Document description
        if (item.description) {
          doc.setFontSize(9);
          doc.setTextColor(100, 100, 100); // Gray color
          const splitDesc = doc.splitTextToSize(item.description, pageWidth - 2 * margin - 10);
          doc.text(splitDesc, margin + 10, yPosition);
          yPosition += splitDesc.length * 4 + 3;
        }
        
        doc.setFontSize(10);
        doc.setTextColor(0, 0, 0); // Reset to black
        yPosition += 2;
      });
    } else {
      doc.setFontSize(10);
      doc.text("No specific documents listed for this license.", margin + 5, yPosition);
      yPosition += 10;
    }

    // Add spacing between licenses
    yPosition += 10;
    
    // Add separator line (except for last item)
    if (index < selectedLicenses.length - 1) {
      if (yPosition > 260) {
        doc.addPage();
        yPosition = 20;
      }
      doc.setDrawColor(200, 200, 200);
      doc.line(margin, yPosition, pageWidth - margin, yPosition);
      yPosition += 15;
    }
  });

  // Add footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth - margin - 20,
      doc.internal.pageSize.height - 10
    );
  }

  // Save the PDF
  doc.save("PRONTO360-Document-Checklist.pdf");
}